// ---------------------------------------------------------------------------
// src/world/hudson/planta.js — A PLANTA DA QUADRA HUDSON.
//
// GERADO a partir da leitura das 35 fotos do Street View de Paracatu-MG. Cada
// lote foi lido do endereco que aparece no cabecalho da foto, e a ordem e a da
// numeracao real da rua.
//
// ISTO E DADO, NAO CODIGO. Quem transforma em geometria e lotes.js. A separacao
// e proposital: corrigir a cor de um muro depois de olhar melhor uma foto tem
// que ser trocar uma string aqui, e nunca mexer em three.js.
//
// O que cada rua fechou:
//
//   R. Frei Pedro Caixito     6 lotes   quarteirao 118.0 m   oposto 118.0 m
//   R. Josue Felix Caixeta   14 lotes   quarteirao 107.0 m   oposto  92.0 m
//   R. Jorge Araujo Caldas   15 lotes   quarteirao 124.0 m   oposto 124.0 m
//   R. Padre Josino          14 lotes   quarteirao 118.0 m   oposto 116.0 m
//
// O campo `_` de cada lote e a INSTRUCAO DE CONSTRUCAO em texto, do jeito que
// saiu da leitura da foto. Nao e lido por ninguem: esta ali pra quem for
// conferir um lote contra a foto dele nao ter que abrir outro arquivo.
// ---------------------------------------------------------------------------

/** As quatro ruas do quarteirao e os lotes de cada uma. */
export const PLANTA = {
  norte: {
    nome: 'R. Frei Pedro Caixito',
    asfalto: 8,
    calcada: 3.6,
    faixa: 'continua',
    postes: 'Todos os postes de iluminacao publica ficam do lado do MURO (calcada oposta): poste de concreto de secao retangular, ~9 m, cinza #9a968c, a cada ~32 m, com braco curvo de 2,5 m atravessando e jogando ',
    declive: 'Praticamente plana ao longo do quarteirao, com caimento suave de ~2% no sentido CRESCENTE da numeracao (172 mais alto, 284 mais baixo). Pass',
    lotes: [
      {
        id: 'caixito-praca-arborizada',
        numero: '150',
        ordem: 1,
        ladoDaRua: 'quarteirao',
        frente: 30,
        tipo: 'praca',
        muro: {
          altura: 0,
          cor: '',
          acabamento: 'sem muro - praca aberta pra rua',
          concertina: false,
        },
        extras: [
          'grama seca amarelada #a89a63 com falhas de terra ocre #b06034',
          'folhas secas acumuladas na calcada e no meio-fio',
          'mato brotando nas juntas transversais das placas de concreto',
          'poste alto proprio da praca (fuste reto claro ~9 m) no gramado a 8 m do meio-fio',
          'sombra malhada das mangueiras caindo sobre calcada e asfalto',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 7,
            offsetX: -12,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 7.5,
            offsetX: -6,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 8,
            offsetX: 0,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 6.5,
            offsetX: 6,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 7,
            offsetX: 12,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-24',
          'foto-33',
        ],
        confianca: 'media',
        _: 'Ponta arborizada da praca publica, na esquina baixa do quarteirao: SEM muro, SEM portao, SEM edificacao - o lote e aberto pra rua e essa abertura e o ',
      },
      {
        id: 'caixito-quadra-coberta',
        numero: '172',
        ordem: 3,
        ladoDaRua: 'quarteirao',
        frente: 26,
        tipo: 'quadra-coberta',
        muro: {
          altura: 4,
          cor: '#9aa0a0',
          acabamento: 'alambrado de tela galvanizada malha losangular sobre montantes tubulares a cada 2,5 m, sem mureta',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 7,
          recuo: 13,
          profundidade: 30,
          parede: '#e2e2dd',
          telha: 'telha metalica trapezoidal branca #f0ece5',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas rasas metalicas com testeira cega frontal',
          cor: '#f0ece5',
          cumeeira: 12,
          beiral: 1.2,
        },
        extras: [
          'testeira de chapa trapezoidal branca com nervuras verticais, cega, topo a 12 m',
          'tesouras metalicas trelicadas aparentes cor creme sob a cobertura',
          'piso da quadra com pintura verde-agua e terracota desbotada e pocas de agua',
          'tabela de basquete azul-marinho escura em poste azul independente',
          'tabela de basquete branca com aro laranja no fundo da quadra',
          'exaustor circular escuro no alto do muro de fundo bege',
          'moita alta (oleandro) encostada no alambrado, tapando parte da tela',
          'mato nas juntas da calcada larga de concreto',
        ],
        arvores: [
          {
            especie: 'moita',
            altura: 3.5,
            offsetX: 9,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 6.5,
            offsetX: -11,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-26',
          'foto-34',
        ],
        confianca: 'alta',
        _: 'Ginasio aberto (quadra poliesportiva coberta) - o volume que domina esta metade da rua. Na frente NAO ha muro: calcada de concreto larguissima de 3,8 ',
      },
      {
        id: 'caixito-praca-esportiva',
        numero: '220',
        ordem: 4,
        ladoDaRua: 'quarteirao',
        frente: 26,
        tipo: 'praca',
        muro: {
          altura: 4,
          cor: '#9aa0a0',
          acabamento: 'alambrado galvanizado de 4 m recuado 4 m do meio-fio, interrompido no trecho central',
          concertina: false,
        },
        extras: [
          'lateral da pista de skate inteiramente grafitada em azul-cobalto e vermelho com contorno branco',
          'guarda-corpo metalico cinza de 1,0 m sobre a plataforma de skate',
          'quiosque de telhado piramidal metalico verde-escuro com bancos por baixo',
          'tenda de lona bege desbotada, manchada e caida num canto, sobre estrutura tubular',
          'bancos coloridos vermelho e amarelo sob a tenda',
          'bloco de concreto grafitado ao lado da tenda',
          '5 aparelhos de academia ao ar livre em tubo metalico cinza com detalhes amarelos e verdes',
          'caminhos de bloquete intertravado terracota cortando o gramado seco',
          'grama seca amarelada com falhas de terra ocre exposta',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 6,
            offsetX: -12,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-26',
          'foto-28',
        ],
        confianca: 'alta',
        _: 'Miolo da praca: aberto pra rua, sem muro e sem portao. Repita a calcada de concreto de 3,8 m em placas de 1,5 m #c0bbaf com juntas escuras e mato, e o',
      },
      {
        id: 'caixito-edificio-publico-284',
        numero: '284',
        ordem: 6,
        ladoDaRua: 'quarteirao',
        frente: 36,
        tipo: 'escola',
        muro: {
          altura: 1,
          cor: '#b5613c',
          acabamento: 'mureta de 1,0 m com mural pintado em terracota, amarelo e azul; atras, gradil metalico verde-escuro de 1,8 m sobre mureta',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 3.6,
          recuo: 15,
          profundidade: 18,
          parede: '#ded4ba',
          telha: 'cobertura plana escondida por platibanda reta',
          varanda: true,
        },
        telhado: {
          tipo: 'laje plana com platibanda reta continua, sem beiral',
          cor: '#e2dcc6',
          cumeeira: 4.2,
          beiral: 0,
        },
        extras: [
          '4 condensadoras de ar-condicionado split na fachada com escorrimento escuro descendo do reboco abaixo de cada uma',
          'marquise metalica azul-marinho quase preta em balanco sobre a entrada',
          'mureta de 1,0 m coberta por mural pintado em terracota, amarelo e azul',
          'gradil metalico verde-escuro de 1,8 m sobre mureta fechando a area de convivencia',
          '4 conjuntos de mesa de concreto com bancos fixos rosa, azul e verde',
          'tamboretes cilindricos de concreto coloridos soltos no gramado',
          'coberta metalica leve sobre pilaretes finos com bancos e parede com murais na ponta',
          'piso de bloquete intertravado terracota contornando o edificio',
          'bancos de concreto retangulares simples sem encosto junto ao bloquete',
          'platibanda reta continua sem beiral nenhum',
        ],
        arvores: [
          {
            especie: 'moita',
            altura: 1.6,
            offsetX: 14,
            ondeFica: 'recuo',
          },
        ],
        fotos: [
          'foto-28',
          'foto-35',
        ],
        confianca: 'alta',
        _: 'Edificio publico terreo e longuissimo (centro comunitario / escola) fechando a ponta alta do quarteirao. Na frente, calcada de concreto de 4,0 m em pl',
      },
      {
        id: 'caixito-muro-escola-a',
        numero: 's/n',
        ordem: 2,
        ladoDaRua: 'oposto',
        frente: 62,
        tipo: 'muro-cego',
        muro: {
          altura: 2.2,
          cor: '#ddd8cd',
          acabamento: 'placa pre-moldada de concreto pintada de branco, montantes/pilastras salientes a cada 3,0 m, coroamento reto',
          concertina: false,
        },
        casa: {
          pavimentos: 2,
          pedireito: 3,
          recuo: 12,
          profundidade: 14,
          parede: '#b3a888',
          telha: 'fibrocimento cinza #8f9490, duas aguas de baixa inclinacao',
          varanda: true,
        },
        telhado: {
          tipo: 'duas aguas de baixa inclinacao em fibrocimento',
          cor: '#8f9490',
          cumeeira: 7,
          beiral: 0.6,
        },
        extras: [
          'mancha cinza de umidade escorrendo do topo em cada painel do muro',
          'barra inferior de 0,40 m suja de terra vermelha respingada de chuva',
          'tinta branca descascando em placas junto aos montantes',
          'fila de 12 balizadores de concreto brancos de 0,70 m no meio-fio, a cada 2,5 m, alguns tortos',
          'faixa de terra vermelha compactada de 1,2 m entre meio-fio e muro, com capim rasteiro',
          'poste de concreto de 9 m com braco curvo atravessando a pista, a cada 32 m',
          'cabo de fibra optica cruzando a rua na diagonal',
        ],
        fotos: [
          'foto-24',
          'foto-33',
          'foto-34',
        ],
        confianca: 'alta',
        _: 'Testada 100% fechada, sem uma unica abertura: paredao cego de placas pre-moldadas de concreto pintadas de BRANCO #ddd8cd, 2,2 m de altura, encaixadas ',
      },
      {
        id: 'caixito-muro-escola-b',
        numero: 's/n',
        ordem: 5,
        ladoDaRua: 'oposto',
        frente: 56,
        tipo: 'muro-cego',
        muro: {
          altura: 2.2,
          cor: '#dcd6c9',
          acabamento: 'alvenaria rebocada pintada de branco encardido, pilastras salientes a cada 3,0 m, coroamento reto; termina em alambrado de tela escura sobre mureta de 0,5 m',
          concertina: false,
        },
        telhado: {
          tipo: 'cobertura metalica de galpao sobre trelicas azuis, atras do muro',
          cor: '#c9ccc7',
          cumeeira: 6.5,
          beiral: 0.8,
        },
        extras: [
          'manchas de umidade e mofo SUBINDO da base do muro em ondas de 0,8 m',
          'manchas cinza descendo do topo do muro em cada pano entre pilastras',
          'areas de reboco cru exposto onde a tinta caiu',
          'pichacoes escuras rasas no muro',
          'trecho de 8 m em que o muro sobe de 2,2 para 2,6 m',
          'trelicas metalicas azuis do galpao esportivo aparecendo por cima do muro',
          'trecho final fechado por alambrado de tela escura sobre mureta de 0,5 m',
          'poste de concreto com caixa de emenda de telecom no fuste',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 8,
            offsetX: -18,
            ondeFica: 'quintal',
          },
        ],
        fotos: [
          'foto-35',
          'foto-34',
        ],
        confianca: 'media',
        _: 'Continuacao do mesmo paredao cego, mas mais castigado - trate como uma testada distinta. Muro de alvenaria rebocada e pintada de branco ja acinzentado',
      },
    ],
  },
  sul: {
    nome: 'R. Josue Felix Caixeta',
    asfalto: 7,
    calcada: 1.8,
    faixa: 'continua',
    postes: 'postes de concreto de secao retangular #9a958c no lado do quarteirao (lado das casas), cravados na calcada, espacados uns 30 m, com braco curvo e luminaria; carregam um emaranhado denso de cabos, rolo',
    declive: 'a rua cai no sentido dos numeros menores (do 300 para o 241), suave no meio do quarteirao e mais forte depois da esquina baixa, abrindo para',
    lotes: [
      {
        id: 'caixeta-oposto-esquina-centro-comunitario',
        ordem: 12,
        ladoDaRua: 'quarteirao',
        frente: 22,
        tipo: 'comercio',
        muro: {
          altura: 0,
          cor: '#d5cbb0',
          acabamento: 'sem muro; edificacao publica solta no lote',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 3.6,
          recuo: 2,
          profundidade: 14,
          parede: '#d5cbb0',
          telha: 'laje escondida atras da platibanda',
          varanda: false,
        },
        telhado: {
          tipo: 'laje com platibanda reta',
          cor: '#c2b79a',
          cumeeira: 4.5,
          beiral: 0,
        },
        extras: [
          'oculo circular escuro no alto do pano cego',
          'marquise de chapa metalica cinza-escuro projetando 2 m',
          'pano continuo de esquadrias de aluminio com vidro verde',
          'escorridos verticais escuros descendo da platibanda',
          'banco de concreto com assento vermelho na terra',
          'faixa de terra batida ocre entre o predio e o meio-fio',
        ],
        arvores: [
          {
            especie: 'coqueiro',
            altura: 10,
            offsetX: 2,
            ondeFica: 'terreno',
          },
          {
            especie: 'moita',
            altura: 1.4,
            offsetX: -6,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-01',
          'foto-02',
        ],
        confianca: 'alta',
        _: 'Equipamento publico de esquina (centro comunitario), na ponta baixa do quarteirao, sem muro e sem recuo lateral. Erga um BLOCO CEGO retangular de 22 m',
      },
      {
        id: 'caixeta-oposto-quadra-coberta-praca',
        ordem: 13,
        ladoDaRua: 'quarteirao',
        frente: 35,
        tipo: 'praca',
        muro: {
          altura: 1.7,
          cor: '#c9c2b2',
          acabamento: 'mureta de concreto de 0,5 m encimada por alambrado metalico de 1,2 m',
          concertina: false,
        },
        telhado: {
          tipo: 'cobertura metalica em duas aguas rasas com lanternim',
          cor: '#eceff1',
          cumeeira: 8.5,
          beiral: 1,
        },
        extras: [
          'lanternim elevado na crista da cobertura',
          'pilares metalicos brancos de secao quadrada, sem fechamento lateral',
          'mureta de concreto com alambrado no perimetro',
          'modulos de rampa de skate com faixas rosa e azul',
          'capim seco nas juntas do concreto',
        ],
        arvores: [
          {
            especie: 'moita',
            altura: 2,
            offsetX: -12,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-01',
          'foto-02',
        ],
        confianca: 'alta',
        _: 'Patio de terra e concreto da frente do complexo. A quadra coberta fica la atras, a 30-35 m, e da pra Frei Pedro Caixito.',
      },
      {
        id: 'caixeta-oposto-escola',
        ordem: 14,
        ladoDaRua: 'quarteirao',
        frente: 50,
        tipo: 'escola',
        muro: {
          altura: 1.2,
          cor: '#efeee9',
          acabamento: 'mureta de arrimo branca no talude + gradil de montantes brancos com paineis vazados no trecho de esquina',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 5.2,
          recuo: 8,
          profundidade: 25,
          parede: '#ded4bb',
          telha: 'laje escondida atras da platibanda',
          varanda: false,
        },
        telhado: {
          tipo: 'cobertura plana escondida por platibanda reta continua',
          cor: '#c2b498',
          cumeeira: 5.2,
          beiral: 0,
        },
        extras: [
          'escorridos verticais de chuva marcando toda a parede cega creme',
          'faixa continua de esquadrias quadriculadas com montantes claros',
          'rampas/contrafortes de concreto inclinados encostados na fachada',
          'condensadora split e quadro eletrico na parede cega',
          'patio de concreto com juntas e caminho de bloquete vermelho',
          'bancos de concreto com assento vermelho-terracota',
          'paraciclo de arcos metalicos vermelhos',
          'talude gramado seco com mureta de arrimo branca',
          'gradil de montantes brancos com paineis vazados na esquina',
          'poste alto galvanizado de iluminacao com braco longo',
          'meio-fio de concreto continuo',
        ],
        arvores: [
          {
            especie: 'aroeira-salsa',
            altura: 8,
            offsetX: -14,
            ondeFica: 'recuo',
          },
          {
            especie: 'aroeira-salsa',
            altura: 8.5,
            offsetX: 0,
            ondeFica: 'recuo',
          },
          {
            especie: 'aroeira-salsa',
            altura: 8,
            offsetX: 16,
            ondeFica: 'recuo',
          },
        ],
        fotos: [
          'foto-06',
          'foto-08',
          'foto-09',
          'foto-10',
        ],
        confianca: 'alta',
        _: 'ESCOLA / equipamento institucional ocupando toda a parte alta do lado oposto ate a esquina com a R. Jorge Araujo Caldas, recuo de 8 m do meio-fio. Erg',
      },
      {
        id: 'caixeta-241-oficina-da-barba',
        numero: '241',
        ordem: 1,
        ladoDaRua: 'oposto',
        frente: 12,
        tipo: 'comercio',
        muro: {
          altura: 0,
          cor: '#d7c4a4',
          acabamento: 'sem muro, fachada comercial na divisa',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 3.2,
          recuo: 0,
          profundidade: 8,
          parede: '#d7c4a4',
          telha: 'laje escondida atras da testeira',
          varanda: false,
        },
        telhado: {
          tipo: 'laje com platibanda/testeira reta',
          cor: '#23272e',
          cumeeira: 4.8,
          beiral: 0,
        },
        extras: [
          'testeira/letreiro alto em painel escuro com letras douradas',
          'painel com cabeca de leao dourada entre as vitrines',
          'calcada nova em ceramica vermelha com degrau de 10 cm',
          'poste de concreto de esquina com rolos de fibra otica e caixa CTO branca',
          'emaranhado denso de cabos aereos saindo do poste em leque',
        ],
        fotos: [
          'foto-07',
        ],
        confianca: 'alta',
        _: 'Loja de esquina, recuo ZERO, fachada na divisa. Erga um bloco terreo de 12 m de testada x 8 m de profundidade, pe-direito 3,2 m, reboco liso bege-arei',
      },
      {
        id: 'caixeta-243-sena-griffes',
        numero: '243',
        ordem: 2,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'comercio',
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.6,
            cor: '#6c6862',
            ferrugem: 0.15,
            offsetX: -2.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 3,
          recuo: 0,
          profundidade: 7,
          parede: '#ddcfb3',
          telha: 'laje escondida',
          varanda: false,
        },
        telhado: {
          tipo: 'laje com testeira reta',
          cor: '#1e2430',
          cumeeira: 4.4,
          beiral: 0,
        },
        extras: [
          'testeira escura com letras douradas e coluna classica',
          'porta social estreita escura ao lado do portao',
          'degrau de 12 cm na calcada',
        ],
        fotos: [
          'foto-07',
          'foto-05',
        ],
        confianca: 'alta',
        _: 'Loja colada a esquerda da barbearia, mesma linha de divisa, recuo zero. Bloco terreo de 8 m x 7 m, pe-direito 3,0 m, reboco pintado creme #ddcfb3 mais',
      },
      {
        id: 'caixeta-244-tapecaria-tok-certo',
        numero: '244',
        ordem: 3,
        ladoDaRua: 'oposto',
        frente: 12,
        tipo: 'comercio',
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.8,
            altura: 2.5,
            cor: '#a1968a',
            ferrugem: 0.35,
            offsetX: -3.6,
          },
          {
            tipo: 'chapa-correr',
            largura: 3.2,
            altura: 2.6,
            cor: '#9c9186',
            ferrugem: 0.3,
            offsetX: 3.4,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 3.2,
          recuo: 0,
          profundidade: 10,
          parede: '#ded1b6',
          telha: 'fibrocimento escondido atras da lona',
          varanda: false,
        },
        telhado: {
          tipo: 'uma agua de fibrocimento escondida atras do banner',
          cor: '#a9a49a',
          cumeeira: 4.4,
          beiral: 0.2,
        },
        extras: [
          'banner/lona gigante marrom com letras douradas acima da fachada',
          'vao central aberto com interior escuro e escada de madeira encostada',
          'caixa de padrao de energia cinza com portinhola marrom e eletroduto',
          'tambor branco encardido em pe na calcada',
          'fileira de bancos automotivos usados empilhados na calcada',
          'mofo e escorrido escuro descendo do topo da parede',
        ],
        arvores: [
          {
            especie: 'tuia',
            altura: 6,
            offsetX: -5.5,
            ondeFica: 'quintal',
          },
        ],
        fotos: [
          'foto-05',
        ],
        confianca: 'alta',
        _: 'Galpao/oficina terrea na divisa, recuo zero. Volume unico de 12 m de testada x 10 m de profundidade, parede rebocada creme envelhecido #ded1b6 com man',
      },
      {
        id: 'caixeta-246-casa-caiada',
        numero: '246',
        ordem: 4,
        ladoDaRua: 'oposto',
        frente: 7,
        tipo: 'casa',
        muro: {
          altura: 1.8,
          cor: '#ddd6c6',
          acabamento: 'reboco pintado sujo com rufo de telha ceramica no topo',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          recuo: 0,
          profundidade: 9,
          parede: '#ded6c4',
          telha: 'ceramica colonial capa-e-canal',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas, telha ceramica colonial',
          cor: '#b0512e',
          cumeeira: 4.2,
          beiral: 0.7,
        },
        extras: [
          'beiral com caibros de madeira escura aparentes sobre a calcada',
          'grade de barra vertical na janela',
          'mancha continua de terra vermelha subindo 0,4 m da base do muro',
          'capim na junta da calcada',
          'carreira de telha ceramica como rufo no topo do muro baixo',
        ],
        fotos: [
          'foto-05',
        ],
        confianca: 'alta',
        _: 'Casinha antiga colada a esquerda da tapecaria, recuo zero, fachada na divisa. Parede caiada creme/branco encardido #ded6c4 com barrado inferior mais s',
      },
      {
        id: 'caixeta-250-casa-fundo',
        numero: '250',
        ordem: 5,
        ladoDaRua: 'oposto',
        frente: 6,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#e3ded2',
          acabamento: 'reboco pintado encardido com capeamento reto de argamassa',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.2,
            cor: '#96897a',
            ferrugem: 0.3,
            offsetX: 0.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          recuo: 1.5,
          profundidade: 8,
          parede: '#e3ded2',
          telha: 'ceramica colonial',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas, telha ceramica colonial desalinhada',
          cor: '#a94e2c',
          cumeeira: 4,
          beiral: 0.4,
        },
        extras: [
          'telhas ceramicas desalinhadas e quebradas',
          'faixa de umidade cinza na base do muro',
          'degrau de 15 cm na calcada',
        ],
        fotos: [
          'foto-05',
          'foto-07',
        ],
        confianca: 'media',
        _: 'Casa terrea encostada na anterior, recuada 1,5 m atras de um muro. Muro frontal de 2,2 m rebocado branco-creme #e3ded2 encardido, topo com capeamento ',
      },
      {
        id: 'caixeta-262-bar-faixas',
        numero: '262',
        ordem: 6,
        ladoDaRua: 'oposto',
        frente: 5,
        tipo: 'comercio',
        casa: {
          pavimentos: 1,
          pedireito: 3,
          recuo: 0,
          profundidade: 6,
          parede: '#c8362b',
          telha: 'fibrocimento atras de platibanda',
          varanda: false,
        },
        telhado: {
          tipo: 'uma agua de fibrocimento atras de platibanda reta',
          cor: '#a9a49a',
          cumeeira: 3.4,
          beiral: 0.1,
        },
        extras: [
          'fachada em faixas vermelha, amarela e branca desbotadas',
          'abertura larga escura sem portao',
          'lixeira de tambor encostada na parede',
          'mato na junta da calcada',
        ],
        fotos: [
          'foto-04',
          'foto-10',
        ],
        confianca: 'baixa',
        _: 'Ponto comercial pequeno (bar/mercearia) na divisa, recuo zero, 5 m de testada x 6 m de profundidade. Fachada pintada em TRES FAIXAS HORIZONTAIS: base ',
      },
      {
        id: 'caixeta-270-tapume-laranja',
        numero: '270',
        ordem: 7,
        ladoDaRua: 'oposto',
        frente: 4,
        tipo: 'terreno-vazio',
        muro: {
          altura: 2.4,
          cor: '#b5522c',
          acabamento: 'chapa metalica corrugada vertical enferrujada',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 4,
            altura: 2.4,
            cor: '#b5522c',
            ferrugem: 0.5,
            offsetX: 0,
          },
        ],
        extras: [
          'tapume de chapa corrugada laranja-ferrugem com topo irregular',
          'empenas de reboco cru dos vizinhos aparecendo dos dois lados',
          'monte de areia e entulho no pe do tapume',
          'capim alto no terreno',
        ],
        fotos: [
          'foto-04',
        ],
        confianca: 'media',
        _: 'Vao de terreno fechado na testada por um TAPUME/PORTAO alto de chapa metalica corrugada vertical pintada de laranja-ferrugem #b5522c, 4,0 m de largura',
      },
      {
        id: 'caixeta-278-borracharia',
        numero: '278',
        ordem: 8,
        ladoDaRua: 'oposto',
        frente: 7,
        tipo: 'comercio',
        casa: {
          pavimentos: 1,
          pedireito: 2.6,
          recuo: 0,
          profundidade: 8,
          parede: '#b98d6a',
          telha: 'fibrocimento ondulado',
          varanda: false,
        },
        telhado: {
          tipo: 'uma agua de fibrocimento ondulado',
          cor: '#c5c6c1',
          cumeeira: 3.2,
          beiral: 0.6,
        },
        extras: [
          'vao aberto sem portao com interior preto',
          'pilhas de pneus pretos na parede e na calcada',
          'manchas de oleo escuro na base da parede e no piso da calcada',
          'reboco cru caindo perto do vao',
        ],
        fotos: [
          'foto-03',
          'foto-04',
        ],
        confianca: 'alta',
        _: 'Borracharia/oficina no alinhamento da rua, recuo zero. Volume baixo de 7 m x 8 m com um VAO ABERTO largo de 3,0 x 2,4 m sem portao, interior totalment',
      },
      {
        id: 'caixeta-288-casa-salmao',
        numero: '288',
        ordem: 9,
        ladoDaRua: 'oposto',
        frente: 10,
        tipo: 'casa',
        casa: {
          pavimentos: 1,
          pedireito: 3.2,
          recuo: 0,
          profundidade: 10,
          parede: '#bd5b45',
          telha: 'ceramica colonial',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com empena virada para a rua',
          cor: '#b5613a',
          cumeeira: 5.5,
          beiral: 0.4,
        },
        extras: [
          'empena alta rebocada virada para a rua',
          'tabica vermelha aparente no beiral',
          'antena parabolica branca no telhado',
          'caixa d\'agua azul sobre base de alvenaria no fundo do telhado',
          'faixa de umidade cinza-esverdeada na base da parede',
        ],
        fotos: [
          'foto-03',
          'foto-04',
        ],
        confianca: 'alta',
        _: 'Casa terrea de EMPENA ALTA virada para a rua, recuo zero, na divisa. Corpo de 10 m de testada x 10 m de profundidade, parede pintada em salmao-terraco',
      },
      {
        id: 'caixeta-294-casa-varanda',
        numero: '294',
        ordem: 10,
        ladoDaRua: 'oposto',
        frente: 11.5,
        tipo: 'casa',
        muro: {
          altura: 1.2,
          cor: '#d3a681',
          acabamento: 'ceramica tipo tijolinho bege-rosado com junta clara, encimada por gradil de barra vertical branco de 1,0 m',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.9,
          recuo: 3.5,
          profundidade: 11,
          parede: '#efe9dc',
          telha: 'ceramica colonial',
          varanda: true,
        },
        telhado: {
          tipo: 'duas aguas no corpo principal + uma agua na varanda',
          cor: '#b5613a',
          cumeeira: 5,
          beiral: 0.8,
        },
        extras: [
          'mureta revestida em ceramica tipo tijolinho com juntas aparentes',
          'gradil de barra vertical branco sobre a mureta',
          'caixa de medidor de energia embutida na mureta',
          'varanda coberta com telha ceramica e pilaretes brancos',
          'degrau na calcada entre este lote e o vizinho',
        ],
        fotos: [
          'foto-03',
          'foto-04',
        ],
        confianca: 'alta',
        _: 'Casa terrea com VARANDA FRONTAL fechada por gradil, recuo de 3,5 m entre a testada e a fachada. Na testada, uma mureta continua de 1,2 m revestida em ',
      },
      {
        id: 'caixeta-300',
        numero: '300',
        ordem: 11,
        ladoDaRua: 'oposto',
        frente: 9.5,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.6,
          cor: '#b3a795',
          acabamento: 'reboco cru nunca pintado, muito deteriorado, com grandes falhas expondo tijolo ceramico vermelho e mancha de umidade subindo da base',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3.3,
            altura: 2.2,
            cor: '#8a9c46',
            ferrugem: 0.75,
            offsetX: 1.2,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          recuo: 6,
          profundidade: 10,
          parede: '#d8cfbc',
          telha: 'ceramica colonial',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas, telha ceramica colonial (mal visivel atras do muro)',
          cor: '#b5613a',
          cumeeira: 4.6,
          beiral: 0.4,
        },
        extras: [
          'reboco cru caindo em placas expondo tijolo ceramico vermelho',
          'mancha de umidade escura subindo 0,8 m da base do muro',
          'verga de concreto aparente sobre o portao criando degrau no topo do muro',
          'portao de chapa ondulada verde-oliva com escorridos de ferrugem alaranjada',
          'entulho de tijolos e blocos de concreto no pe do muro',
          'rampa de garagem de concreto na calcada',
          'poste de concreto com braco e luminaria na calcada em frente',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 9,
            offsetX: -2,
            ondeFica: 'quintal',
          },
          {
            especie: 'palmeira-leque',
            altura: 3.5,
            offsetX: -4.5,
            ondeFica: 'quintal',
          },
        ],
        fotos: [
          'foto-03',
          'foto-04',
        ],
        confianca: 'alta',
        _: 'MURO CEGO ALTO na testada, 9,5 m de extensao e 2,6 m de altura (2,9 m no trecho da verga). Alvenaria rebocada NUNCA PINTADA: reboco cru cinza-bege #b3',
      },
    ],
  },
  leste: {
    nome: 'R. Jorge Araujo Caldas',
    asfalto: 7,
    calcada: 1.3,
    faixa: 'tracejada',
    postes: 'Do lado das casas (quarteirao): postes de CONCRETO de secao duplo-T, 9 m, a cada ~32 m, com braco curvo de 1,5 m e luminaria de petala; deles saem feixes pesados de cabo de energia e telecom que atrav',
    declive: 'A rua DESCE de norte para sul: do cruzamento com a R. Josue Felix Caixeta (no 240, cota alta) em direcao a R. Padre Josino (no 109, cota bai',
    lotes: [
      {
        id: 'praca-publica-trecho-baixo',
        ordem: 2,
        ladoDaRua: 'quarteirao',
        frente: 45,
        tipo: 'praca',
        extras: [
          'monte de areia de construcao, 4,5 m de base x 1,2 m de altura',
          'pilha organizada de blocos ceramicos vazados encostada no monte de areia',
          'lona plastica azul amassada no chao entre as arvores',
          'entulho branco de alvenaria e restos de construcao espalhados',
          'barranco de terra crua de 0,8 m de desnivel junto ao meio-fio',
          'sacolas plasticas e papeis presos no capim seco',
          'calcada larga de placas de concreto 1x1 m com juntas cheias de mato',
        ],
        arvores: [
          {
            especie: 'cajueiro',
            altura: 6,
            offsetX: -14,
            ondeFica: 'terreno',
          },
          {
            especie: 'cajueiro',
            altura: 4.5,
            offsetX: -5,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 5.5,
            offsetX: 4,
            ondeFica: 'terreno',
          },
          {
            especie: 'cajueiro',
            altura: 4,
            offsetX: 13,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 5,
            offsetX: 19,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-16',
          'foto-23',
          'foto-19',
          'foto-29',
          'foto-18',
        ],
        confianca: 'alta',
        _: 'Faixa publica ABERTA, sem muro e sem cerca, ocupando os 45 m mais baixos da calcada oposta - nada de construcao aqui, o vazio e o que caracteriza o tr',
      },
      {
        id: 'escola-quadra-coberta',
        ordem: 4,
        ladoDaRua: 'quarteirao',
        frente: 28,
        tipo: 'escola',
        muro: {
          altura: 2,
          cor: '#e6e4dd',
          acabamento: 'muro baixo branco fechando o fundo do lote, atras das arvores',
          concertina: false,
        },
        telhado: {
          tipo: 'telha metalica trapezoidal, duas aguas rasas, laterais abertas',
          cor: '#eef0ef',
          cumeeira: 9,
          beiral: 0.8,
        },
        extras: [
          'estrutura metalica do ginasio pintada de LARANJA aparecendo por baixo da telha branca',
          'duas condensadoras split na parede com mancha escura de escorrimento embaixo de cada uma',
          'dois bancos de concreto com pes pintados de vermelho e tampo claro',
          'calcadao de placas de concreto 2,0x2,0 m com juntas escuras',
          'faixa de grama seca com terra aparente entre o calcadao e a edificacao',
          'janelas de aluminio com vidro azulado na parede lateral',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 6,
            offsetX: -11,
            ondeFica: 'terreno',
          },
          {
            especie: 'cajueiro',
            altura: 5,
            offsetX: 8,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-14',
          'foto-16',
          'foto-18',
        ],
        confianca: 'alta',
        _: 'Bloco de salas terreo do complexo, com duas condensadoras split na parede. A quadra coberta esta 55-65 m atras, na outra face.',
      },
      {
        id: 'escola-predio-arcada-talude',
        ordem: 11,
        ladoDaRua: 'quarteirao',
        frente: 51,
        tipo: 'escola',
        muro: {
          altura: 0.6,
          cor: '#cfc6b6',
          acabamento: 'mureta/meio-fio de concreto arrematando a base do talude',
          concertina: false,
        },
        telhado: {
          tipo: 'laje plana escondida por platibanda reta continua',
          cor: '#e5dcc2',
          cumeeira: 5.5,
          beiral: 0,
        },
        extras: [
          'talude gramado de 1,6 m elevando todo o lote acima da calcada, grama seca com terra vermelha exposta',
          'escorrimentos verticais de sujeira descendo da platibanda por toda a fachada',
          'pilares da arcada com perfil INCLINADO, mocheta abrindo em cunha triangular no alto',
          'portoes de grade metalica cinza-escura fechando tres vaos da galeria',
          'escadaria central de concreto aparente com faces laterais em cunha e degraus manchados de umidade',
          'passagem coberta central atravessando o predio, deixando ver o patio interno',
          'pilarete de concreto tronco-piramidal de 1,7 m com caixa de padrao embutida',
          'cinco bancos de concreto com pes pintados de vermelho',
          'bicicletario metalico verde de 2,0x0,9 m',
          'dois cestos de lixo verdes em suporte metalico junto a escada',
          'duas janelinhas verticais estreitas no alto da empena cega, com luminarias enferrujadas',
        ],
        fotos: [
          'foto-12',
        ],
        confianca: 'alta',
        _: 'Trecho alto da calcada oposta: PREDIO PUBLICO (escola/centro comunitario) plantado sobre um TALUDE - comece pelo talude, ele e quem define a cena. Tal',
      },
      {
        id: 'caldas-109-esquina-padre-josino',
        numero: '109',
        ordem: 1,
        ladoDaRua: 'oposto',
        frente: 11,
        tipo: 'sobrado',
        muro: {
          altura: 2.3,
          cor: '#a6a29a',
          acabamento: 'bloco de concreto estrutural APARENTE, sem reboco, juntas 39x19 cm bem marcadas, sujeira escura escorrendo na base',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 5.5,
            altura: 2.2,
            cor: '#dedad1',
            ferrugem: 0.25,
            offsetX: 2.5,
          },
          {
            tipo: 'chapa-batente',
            largura: 0.9,
            altura: 2.1,
            cor: '#c8ccd0',
            ferrugem: 0.1,
            offsetX: -4,
          },
        ],
        casa: {
          pavimentos: 2,
          pedireito: 2.9,
          profundidade: 9,
          recuo: 4,
          parede: '#c6b9a3',
          telha: '#a8542f',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas + volume superior de laje com platibanda reta',
          cor: '#a8542f',
          cumeeira: 3.6,
          beiral: 0.5,
        },
        extras: [
          'sobrado inacabado de 2 pavimentos com volume superior RECUADO, reboco cru sem pintura',
          'vaos de janela do pavimento superior sem esquadria, buracos escuros',
          'trecho de muro de TIJOLO CERAMICO APARENTE (tijolo furado deitado, #a05a44) virando a esquina para a R. Padre Josino',
          'duas plaquinhas brancas pequenas coladas na parte de cima da chapa do portao duplo',
          'escorrimento escuro de umidade descendo do topo do muro de blocos',
          'mato na junta calcada/muro',
        ],
        fotos: [
          'foto-29',
          'foto-25',
        ],
        confianca: 'media',
        _: 'Lote de ESQUINA no canto sul do quarteirao (cruzamento com a R. Padre Josino) - e onde a rua termina em baixo. Erga o muro frontal de BLOCO DE CONCRET',
      },
      {
        id: 'caldas-bloco-aparente-vizinho-esquina',
        ordem: 3,
        ladoDaRua: 'oposto',
        frente: 9,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.3,
          cor: '#a6a29a',
          acabamento: 'bloco de concreto aparente sem reboco, juntas marcadas, barrado de respingo de terra na base',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 10,
          recuo: 3,
          parede: '#ddd8cf',
          telha: '#c0703f',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com espigao central',
          cor: '#c0703f',
          cumeeira: 4.5,
          beiral: 0.5,
        },
        extras: [
          'antena parabolica branca grande e antiga sobre o telhado',
          'caixa de padrao de energia com portinhola cinza enferrujada nas bordas, a 1,4 m',
          'registro de agua pequeno com tampa metalica embutido no muro',
          'mato alto na junta calcada/muro',
          'barrado de terra vermelha respingada ate 0,4 m na base do muro',
        ],
        fotos: [
          'foto-25',
        ],
        confianca: 'media',
        _: 'Continuacao do MESMO pano de muro de bloco de concreto aparente do lote de esquina - mantenha a textura de blocos e a cor #a6a29a, 2,3 m de altura por',
      },
      {
        id: 'caldas-muro-cru-oitao-azul',
        ordem: 5,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2,
          cor: '#918d84',
          acabamento: 'reboco cru sem pintura, escorrimentos escuros de chuva do topo, barrado de respingo de terra na base',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 0.9,
            altura: 2,
            cor: '#e8e5dd',
            ferrugem: 0.05,
            offsetX: -1,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 9,
          recuo: 3.5,
          parede: '#cfc9bd',
          telha: '#b56a45',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com oitao triangular voltado para a rua',
          cor: '#b56a45',
          cumeeira: 4.5,
          beiral: 0.5,
        },
        extras: [
          'frontao/oitao triangular pintado em cinza-azulado escuro (#4a5a6b), unico da rua',
          'escorrimentos verticais escuros descendo do topo do muro cru',
          'barrado de respingo de terra vermelha na base do muro',
          'mato na junta da calcada',
        ],
        fotos: [
          'foto-18',
          'foto-25',
        ],
        confianca: 'media',
        _: 'Muro frontal de REBOCO CRU CINZA, sem pintura nenhuma (#918d84), 2,0 m de altura por 8 m de testada, topo reto e sem cimalha. A superficie tem que fic',
      },
      {
        id: 'caldas-muro-branco-placa',
        ordem: 6,
        ladoDaRua: 'oposto',
        frente: 10,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#d9d7d2',
          acabamento: 'reboco liso pintado, barrado inferior escuro por respingo, trincas finas e remendos de argamassa mais claros',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.2,
            cor: '#e2ded6',
            ferrugem: 0.15,
            offsetX: 1.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 11,
          recuo: 4,
          parede: '#c4bfb4',
          telha: '#a85f42',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#a85f42',
          cumeeira: 4.2,
          beiral: 0.5,
        },
        extras: [
          'antena parabolica grande (1,8 m) montada em cima do telhado',
          'placa de comercio retangular escura parafusada no muro, ao lado do portao',
          'rampa de concreto na calcada em frente ao portao',
          'barrado escuro de respingo ate 0,5 m na base do muro',
        ],
        fotos: [
          'foto-25',
          'foto-23',
        ],
        confianca: 'media',
        _: 'Muro rebocado liso e PINTADO de branco-acinzentado (#d9d7d2), 2,2 m de altura por 10 m de testada - e o unico pano pintado de claro deste trecho baixo',
      },
      {
        id: 'caldas-130-casinha-alinhada',
        numero: '130',
        ordem: 7,
        ladoDaRua: 'oposto',
        frente: 6,
        tipo: 'casa',
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 1.1,
            altura: 2.1,
            cor: '#e4e1da',
            ferrugem: 0.1,
            offsetX: -1.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.5,
          profundidade: 8,
          recuo: 0,
          parede: '#c2b09a',
          telha: '#a85f42',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com beiral largo e madeiramento aparente',
          cor: '#a85f42',
          cumeeira: 3.8,
          beiral: 0.6,
        },
        extras: [
          'janela com grade de barras cruzadas em quadriculado, peitoril a 1,2 m',
          'mancha de umidade cinza subindo 0,8 m da calcada na fachada',
          'caixa de padrao de energia branca com eletroduto aparente descendo pela parede',
          'estrutura metalica azul de barras encostada no pe da parede',
          'madeiramento do beiral aparente por baixo das telhas',
        ],
        fotos: [
          'foto-23',
          'foto-16',
        ],
        confianca: 'alta',
        _: 'Casinha terrea CONSTRUIDA NO ALINHAMENTO da calcada - sem muro e sem recuo, a fachada e a divisa. So 6 m de testada, a menor da rua. Parede rebocada e',
      },
      {
        id: 'caldas-casa-a-pilha-de-tijolo',
        ordem: 8,
        ladoDaRua: 'oposto',
        frente: 12,
        tipo: 'casa',
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.2,
            cor: '#ebe8e1',
            ferrugem: 0.1,
            offsetX: -3.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.6,
          profundidade: 12,
          recuo: 0,
          parede: '#b3aea6',
          telha: '#a85f42',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com beiral largo voltado para a rua',
          cor: '#a85f42',
          cumeeira: 4,
          beiral: 0.6,
        },
        extras: [
          'pilha de tijolo ceramico de 8 furos + blocos de concreto sobre a calcada, 7 m de extensao e 1,1 m de altura',
          'portao de garagem com ondulacao HORIZONTAL (unico da rua)',
          '6 m de pano cego de parede sem nenhuma abertura',
          'parede/platibanda verde-agua (#86ada0) sobressaindo 0,8 m acima do telhado, no fundo do lote',
          'trecho de telha metalica enferrujada de puxadinho atras da cumeeira',
          'coqueiro alto no quintal aparecendo por cima do telhado',
        ],
        arvores: [
          {
            especie: 'coqueiro',
            altura: 8,
            offsetX: 4,
            ondeFica: 'quintal',
          },
        ],
        fotos: [
          'foto-21',
        ],
        confianca: 'alta',
        _: 'Casa terrea LONGA no alinhamento da calcada, sem muro: 12 m de testada, parede de 2,6 m ate o beiral, reboco cinza claro encardido (#b3aea6) sem pintu',
      },
      {
        id: 'caldas-150-muro-verde-trailer',
        numero: '150',
        ordem: 9,
        ladoDaRua: 'oposto',
        frente: 11,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.3,
          cor: '#6e7d55',
          acabamento: 'reboco liso com pintura verde-oliva em bom estado, topo reto, o pano mais conservado da quadra',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.6,
            altura: 2.2,
            cor: '#e2e0da',
            ferrugem: 0.05,
            offsetX: 1,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 11,
          recuo: 4,
          parede: '#e5dfd0',
          telha: '#b8664a',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#b8664a',
          cumeeira: 4.5,
          beiral: 0.5,
        },
        extras: [
          'trailer/quiosque de lanches FIXO sobre a calcada: aluminio escovado, testeira preta, painel amarelo e painel vermelho, caixa de exaustao no teto',
          'faixa de terra batida avermelhada pisoteada entre o trailer e o meio-fio',
          'calcada totalmente obstruida pelo trailer nesse trecho',
        ],
        fotos: [
          'foto-17',
          'foto-19',
          'foto-21',
          'foto-15',
        ],
        confianca: 'media',
        _: 'Muro frontal rebocado LISO e pintado de VERDE-OLIVA/MUSGO (#6e7d55), 2,3 m de altura por 11 m de testada - e o pano mais bem conservado de todo o quar',
      },
      {
        id: 'caldas-160-portao-enferrujado',
        numero: '160',
        ordem: 10,
        ladoDaRua: 'oposto',
        frente: 9,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#a2865a',
          acabamento: 'bloco com reboco cru grosseiro SEM pintura, juntas de bloco visiveis, remendos de cimento cinza',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 4,
            altura: 2.2,
            cor: '#a9573a',
            ferrugem: 0.95,
            offsetX: 2.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 10,
          recuo: 4,
          parede: '#e8e2d2',
          telha: '#b86a45',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#b86a45',
          cumeeira: 4.6,
          beiral: 0.5,
        },
        extras: [
          'portao de duas folhas em chapa corrugada TOTALMENTE ENFERRUJADA, sem tinta, com listras verticais de ferrugem',
          'numero \'160\' pintado a mao em preto na folha do portao',
          'numero \'162\' escrito a mao com spray preto direto no reboco cru do muro',
          'caixa de padrao de energia em nicho lascado, base a 1,35 m',
          'caixa de hidrometro branca grande na base do muro, dentro de um pano de reboco branco',
          'obra parada no quintal: laje inacabada com pilares e ferros de espera aparecendo acima do muro',
          'juntas de bloco aparecendo por baixo do reboco grosseiro',
        ],
        fotos: [
          'foto-19',
          'foto-17',
        ],
        confianca: 'alta',
        _: 'Muro frontal de BLOCO rebocado GROSSEIRAMENTE e SEM PINTURA, cor ocre-terrosa de barro (#a2865a), 2,2 m de altura por 9 m de testada, com as juntas do',
      },
      {
        id: 'caldas-170-octogonos-vermelhos',
        numero: '170',
        ordem: 12,
        ladoDaRua: 'oposto',
        frente: 11,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.3,
          cor: '#efece3',
          acabamento: 'reboco liso pintado de branco-creme com dois grandes octogonos vermelhos foscos e faixa vermelha acima do portao de garagem',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 0.95,
            altura: 2.1,
            cor: '#dedbd4',
            ferrugem: 0.15,
            offsetX: -1,
          },
          {
            tipo: 'chapa-correr',
            largura: 3.6,
            altura: 2.2,
            cor: '#dad7cf',
            ferrugem: 0.1,
            offsetX: 3.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 11,
          recuo: 4,
          parede: '#e8e2d5',
          telha: '#b5613c',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas de baixa inclinacao',
          cor: '#b5613c',
          cumeeira: 4.5,
          beiral: 0.5,
        },
        extras: [
          'dois grandes octogonos vermelhos foscos pintados no muro branco (5,5x1,9 m e 3,4x1,7 m)',
          'numero \'170\' pintado em branco por cima do octogono vermelho da direita',
          'elipse branca com seta/chevron vermelha (logomarca) abaixo do numero',
          'faixa do muro pintada de vermelho, 0,35 m, logo acima do portao de garagem',
          'portao social de chapa ondulada branca encaixado exatamente entre os dois octogonos',
        ],
        fotos: [
          'foto-17',
          'foto-19',
          'foto-15',
          'foto-21',
        ],
        confianca: 'alta',
        _: 'Muro frontal rebocado liso e PINTADO DE BRANCO-CREME (#efece3), 2,3 m de altura por 11 m de testada - e o lote mais visivel da rua, da para ve-lo de u',
      },
      {
        id: 'caldas-190-fachada-tabica-vermelha',
        numero: '190',
        ordem: 13,
        ladoDaRua: 'oposto',
        frente: 9,
        tipo: 'casa',
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 3,
            altura: 2.3,
            cor: '#9aa0a2',
            ferrugem: 0.45,
            offsetX: 1,
          },
          {
            tipo: 'chapa-batente',
            largura: 0.9,
            altura: 2.1,
            cor: '#8d9295',
            ferrugem: 0.2,
            offsetX: 3.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 3,
          profundidade: 12,
          recuo: 0,
          parede: '#b2a794',
          telha: '#c2653c',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com madeiramento aparente sob o beiral',
          cor: '#c2653c',
          cumeeira: 4.8,
          beiral: 0.55,
        },
        extras: [
          'testeira/tabica do beiral PINTADA DE VERMELHO correndo por toda a fachada',
          'madeiramento (caibros) aparente por baixo das telhas',
          'caixa de padrao de energia com portinhola aberta e ferragem enferrujada',
          'nicho quadrado com plaqueta escura a 2,0 m do chao',
          'DUAS caixas de hidrometro embutidas rente ao chao, cada uma com registro azul',
          'porta pedestre recuada 30 cm com alizar saliente pintado de claro',
          'mancha cinza de umidade subindo 0,7 m da calcada na fachada',
        ],
        fotos: [
          'foto-13',
          'foto-15',
        ],
        confianca: 'alta',
        _: 'Casa com a FACHADA NO ALINHAMENTO da calcada, sem muro e sem recuo - a parede da casa e a divisa. 9 m de testada, parede frontal de 3,0 m em reboco be',
      },
      {
        id: 'caldas-200-muro-cru-moita-roxa',
        numero: '200',
        ordem: 14,
        ladoDaRua: 'oposto',
        frente: 10,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.3,
          cor: '#b0a591',
          acabamento: 'reboco liso sem pintura, cinta de coroamento em filete de cimento aparente mais claro no topo, mancha de umidade em onda subindo da base',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 1,
            altura: 2,
            cor: '#ded3bb',
            ferrugem: 0.8,
            offsetX: -4,
          },
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.2,
            cor: '#efe7d5',
            ferrugem: 0.2,
            offsetX: 3,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          profundidade: 11,
          recuo: 3,
          parede: '#a9a294',
          telha: '#b4552f',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com empena cega voltada para a rua',
          cor: '#b4552f',
          cumeeira: 4.6,
          beiral: 0.4,
        },
        extras: [
          'numero \'200\' pintado a mao em preto, algarismos de 40 cm, no alto do muro',
          'cinta/filete de cimento aparente mais claro coroando o topo do muro',
          'grande mancha clara de umidade em forma de onda subindo 0,9 m da base do muro',
          'faixa escura de limo rente ao chao na base do muro',
          'portao pedestre de chapa ondulada MUITO enferrujado, com escorrimentos marrons',
          'moita densa de flores ROXAS transbordando do recuo por cima do muro, cobrindo metade do portao pedestre',
          'trilho superior de tubo enferrujado por cima do portao de garagem',
          'duas janelinhas altas e pequenas na empena cega da casa',
          'duas antenas parabolicas brancas grandes sobre os telhados do fundo',
        ],
        arvores: [
          {
            especie: 'moita',
            altura: 3,
            offsetX: -4.5,
            ondeFica: 'recuo',
          },
        ],
        fotos: [
          'foto-13',
          'foto-15',
        ],
        confianca: 'alta',
        _: 'Muro frontal alto de alvenaria rebocada lisa, SEM PINTURA RECENTE, bege-acinzentado encardido (#b0a591), 2,3 m de altura por 10 m de testada, com coro',
      },
      {
        id: 'caldas-240-esquina-josue-felix',
        numero: '210',
        ordem: 15,
        ladoDaRua: 'oposto',
        frente: 18,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.4,
          cor: '#b3a591',
          acabamento: 'reboco liso envelhecido NUNCA pintado, capeamento reto de argamassa no topo, escorrimentos verticais escuros e faixa de umidade/limo subindo 0,8 m da base',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.6,
            altura: 2.2,
            cor: '#c9bda0',
            ferrugem: 0.6,
            offsetX: 7,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 3,
          profundidade: 14,
          recuo: 5,
          parede: '#ece7dc',
          telha: '#c4643c',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com empena/oitao virado para a rua, cumeeira capa-e-canal',
          cor: '#c4643c',
          cumeeira: 5.2,
          beiral: 0.5,
        },
        extras: [
          'numero \'240\' pintado a mao em preto no alto do muro, perto da esquina',
          'nicho retangular VAZIO embutido no muro com mancha de ferrugem alaranjada escorrendo abaixo',
          'caixa de hidrometro com registro azul rente ao chao, na base do muro',
          'faixa continua de umidade/limo escuro subindo 0,8 m da calcada por todo o muro',
          'escorrimentos verticais escuros descendo do capeamento do topo',
          'forte mancha cinza de mofo na faixa inferior da empena da casa',
          'antena parabolica branca antiga sobre o telhado',
          'mangueira jovem de copa densa na calcada, tronco encostado no muro junto ao portao',
          'folhas secas e entulho acumulados no pe do muro',
          'mato na junta entre a calcada e o muro',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 4.5,
            offsetX: 6,
            ondeFica: 'calcada',
          },
        ],
        fotos: [
          'foto-11',
          'foto-09',
          'foto-10',
        ],
        confianca: 'alta',
        _: 'Lote de ESQUINA no canto norte do quarteirao (cruzamento com a R. Josue Felix Caixeta) - a testada em Caldas e longa, 18 m, e fecha a rua por cima. Mu',
      },
    ],
  },
  oeste: {
    nome: 'R. Padre Josino',
    asfalto: 7,
    calcada: 1.2,
    faixa: 'continua',
    postes: 'Postes de CONCRETO de secao circular, todos no lado LESTE (o lado da praca), cravados dentro do gramado a ~1,0 m do meio-fio; espacamento de ~35 m, altura ~9 m, com braco curvo de ~2,5 m avancando sob',
    declive: 'A rua DESCE suavemente no sentido dos numeros crescentes (do lado do no 80 / R. Frei Pedro Caixito para o lado do no 281 / R. Jorge Araujo C',
    lotes: [
      {
        id: 'josino-praca-leste',
        numero: 's/n',
        ordem: 1,
        ladoDaRua: 'quarteirao',
        frente: 118,
        tipo: 'praca',
        muro: {
          altura: 0,
          cor: '#eeece4',
          acabamento: 'sem muro na frente - so meio-fio; o muro branco de 2,0 m com alambrado verde fica a 65 m, no fundo do lote',
          concertina: false,
        },
        extras: [
          'abrigo de onibus de chapa cinza sobre dois montantes marrom-ferrugem, com banco metalico verde-escuro e lixeira verde',
          'placa branca vertical com grafismo vermelho/laranja ao lado do abrigo',
          'lixo plastico branco espalhado pelo capim seco, mais denso perto do meio-fio',
          'monte de entulho vegetal (galhada seca) empurrado contra o meio-fio nas duas extremidades',
          'cacos de tijolo ceramico e pedacos de meio-fio quebrado jogados na terra',
          'boca de lobo com grelha de barras transversais escuras entupida de terra, no meio-fio',
          'bloco irregular de concreto (~0,9 x 0,6 m) largado no pe de um poste',
          'manchas de terra vermelha batida onde o capim morreu, formando trilhas de pedestre atravessando a praca',
          'muro branco de fundo com alambrado verde-escuro, base manchada de terra vermelha',
          'quadra poliesportiva coberta branca ao fundo, testeira alta e pilares metalicos brancos',
          'meio-fio de concreto com faixa de sarjeta de 0,7 m, sem calcada',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 6,
            offsetX: -48,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 4.5,
            offsetX: -30,
            ondeFica: 'terreno',
          },
          {
            especie: 'moita',
            altura: 1.8,
            offsetX: -22,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 3.5,
            offsetX: -8,
            ondeFica: 'terreno',
          },
          {
            especie: 'moita',
            altura: 2,
            offsetX: 2,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 5,
            offsetX: 14,
            ondeFica: 'terreno',
          },
          {
            especie: 'moita',
            altura: 1.6,
            offsetX: 24,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 7,
            offsetX: 38,
            ondeFica: 'terreno',
          },
          {
            especie: 'mangueira',
            altura: 6.5,
            offsetX: 52,
            ondeFica: 'terreno',
          },
        ],
        fotos: [
          'foto-20',
          'foto-22',
          'foto-30',
          'foto-31',
          'foto-32',
        ],
        confianca: 'alta',
        _: 'TODO o lado leste do quarteirao e UM UNICO lote publico: uma praca/area verde aberta de 118 m de testada por ~65 m de profundidade, SEM muro, SEM cerc',
      },
      {
        id: 'josino-205-concertina',
        numero: '205',
        ordem: 2,
        ladoDaRua: 'oposto',
        frente: 14,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.3,
          cor: '#b5a68d',
          acabamento: 'chapisco grosso cru sem pintura, juntas de bloco aparentes, faixa de 3 fiadas de tijolo ceramico aparente (#a8624a) no terco superior, remendos de argamassa cinza',
          concertina: true,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.8,
          recuo: 0.8,
          profundidade: 10,
          parede: '#8f9296',
          telha: 'ceramica colonial capa-e-canal #b5623a, envelhecida #9a4f2d',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas, cumeeira paralela a rua',
          cor: '#b5623a',
          beiral: 0.4,
          cumeeira: 4.2,
        },
        extras: [
          'concertina em espiral sobre mao-francesa de ferro inclinada, coroando o muro',
          'faixa de tijolo ceramico aparente no topo do muro, sem reboco',
          'entulho no pe do muro: telhas de fibrocimento quebradas, isopor branco, cacos de telha',
          'mato na junta da calcada de concreto rustico',
          'beiral de telha colonial avancando 40 cm sobre o muro, pontas de caibro aparentes',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'alta',
        _: 'Muro no alinhamento da calcada, 2,3 m de altura, e o lote mais marcante da rua. O corpo do muro e CHAPISCO GROSSO CRU sem pintura nenhuma, textura mui',
      },
      {
        id: 'josino-sobrado-inacabado',
        numero: 's/n',
        ordem: 3,
        ladoDaRua: 'oposto',
        frente: 9,
        tipo: 'sobrado',
        muro: {
          altura: 7,
          cor: '#ded5c6',
          acabamento: 'reboco cru claro sem pintura, platibanda escalonada em dois degraus, laje aparente, sem beiral',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.6,
            altura: 2.2,
            cor: '#bacfe0',
            ferrugem: 0.1,
            offsetX: 1,
          },
        ],
        casa: {
          pavimentos: 2,
          pedireito: 3,
          recuo: 0,
          profundidade: 9,
          parede: '#ded5c6',
          telha: 'sem telhado - laje plana com platibanda escalonada',
          varanda: true,
        },
        extras: [
          'platibanda escalonada em degraus no oitao',
          'vao de varanda no pavimento superior sem esquadria, so o buraco escuro e a verga de concreto aparente',
          'janelinha quadrada sem caixilho ao lado do vao da varanda',
          'portao de chapa corrugada azul-clara desbotada',
          'reboco cru manchado de escorrimento, obra parada',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'alta',
        _: 'SOBRADO INACABADO de dois pavimentos, construido no alinhamento da calcada (recuo zero), altura total 7,0 m - e o volume mais alto da rua e serve de m',
      },
      {
        id: 'josino-cerca-pallets',
        numero: 's/n',
        ordem: 4,
        ladoDaRua: 'oposto',
        frente: 7,
        tipo: 'terreno-vazio',
        muro: {
          altura: 1.8,
          cor: '#94765a',
          acabamento: 'cerca improvisada de ripas, tabuas e pallets pregados em mouroes tortos, com vaos entre as pecas',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'madeira',
            largura: 2.5,
            altura: 2.2,
            cor: '#8b6a4c',
            ferrugem: 0,
            offsetX: -2,
          },
        ],
        extras: [
          'portao de madeira de duas folhas desalinhadas, tabuas verticais envelhecidas',
          'cerca de pallets e ripas com vaos, travessas pregadas por fora',
          'mato alto e monte de terra visiveis por entre as tabuas',
          'entulho e mato na junta da calcada',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'alta',
        _: 'Lote fechado de forma PRECARIA, colado no sobrado inacabado. A frente e um PORTAO DE MADEIRA de duas folhas mal alinhadas, tabuas verticais envelhecid',
      },
      {
        id: 'josino-barracao-baixo',
        numero: 's/n',
        ordem: 5,
        ladoDaRua: 'oposto',
        frente: 9,
        tipo: 'muro-cego',
        muro: {
          altura: 2.6,
          cor: '#b0a48c',
          acabamento: 'chapisco/reboco cru sem pintura, pilaretes de alvenaria entre vaos abertos, mancha de terra vermelha subindo da base',
          concertina: false,
        },
        telhado: {
          tipo: 'uma agua rasa em telha ondulada de fibrocimento',
          cor: '#8e8577',
          beiral: 0.25,
          cumeeira: 2.8,
        },
        extras: [
          '3 a 4 vaos retangulares abertos e escuros, sem esquadria',
          'testeira de madeira aparente sob a telha ondulada',
          'mancha de terra vermelha subindo 40 cm da base do muro',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'media',
        _: 'Construcao baixa no alinhamento, mais baixa que os vizinhos: uma sequencia de 3 a 4 VAOS RETANGULARES escuros separados por pilaretes de alvenaria cru',
      },
      {
        id: 'josino-muro-cru-a',
        numero: 's/n',
        ordem: 6,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#b5a68d',
          acabamento: 'chapisco grosso cru sem pintura, juntas de bloco aparentes, remendo de argamassa cinza, degrau de 10 cm na divisa',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 1,
          profundidade: 9,
          parede: '#c9bda6',
          telha: 'ceramica colonial #b5623a',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#b5623a',
          beiral: 0.3,
          cumeeira: 4,
        },
        extras: [
          'janelinha alta e estreita aberta no muro, vao escuro sem esquadria',
          'degrau de 10 cm no topo do muro marcando a divisa',
          'beiral de telha colonial passando por cima do muro',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'baixa',
        _: 'Pano de muro no alinhamento, 2,2 m, do mesmo CHAPISCO GROSSO CRU sem pintura que domina a rua (#b5a68d), com as juntas dos blocos aparecendo e um reme',
      },
      {
        id: 'josino-muro-cru-b',
        numero: 's/n',
        ordem: 7,
        ladoDaRua: 'oposto',
        frente: 7,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.4,
          cor: '#c4b092',
          acabamento: 'chapisco grosso cru sem pintura, coroamento com filete de cimento claro, mancha de umidade escura subindo 50 cm da base',
          concertina: false,
        },
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 1.5,
          profundidade: 9,
          parede: '#c9bda6',
          telha: 'ceramica colonial #b5623a',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#b5623a',
          beiral: 0.2,
          cumeeira: 4,
        },
        extras: [
          'mancha de umidade subindo 50 cm da base do muro',
          'coroamento com filete de cimento mais claro no topo',
          'mato na junta entre calcada e muro',
        ],
        fotos: [
          'foto-30',
        ],
        confianca: 'baixa',
        _: 'Mais um pano de muro cru no alinhamento, ligeiramente MAIS ALTO e MAIS CLARO que o vizinho (2,4 m, #c4b092), mesmo chapisco grosso sem pintura, com um',
      },
      {
        id: 'josino-281',
        numero: '281',
        ordem: 8,
        ladoDaRua: 'oposto',
        frente: 11,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#c4b092',
          acabamento: 'chapisco grosso cru sem pintura, base mais lisa ate 1,2 m e topo mais rugoso, juntas de bloco aparentes, placa pintada com o numero 281',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 1,
            altura: 2,
            cor: '#6f8f6a',
            ferrugem: 0.2,
            offsetX: -5.2,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 0.6,
          profundidade: 10,
          parede: '#c9bda6',
          telha: 'ceramica colonial #b5623a, telhas gastas #9a4f2d',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas, cumeeira paralela a rua',
          cor: '#b5623a',
          beiral: 0.3,
          cumeeira: 3.8,
        },
        extras: [
          'numero \'281\' pintado a mao em retangulo claro no muro, a 1,4 m do chao',
          'CAIXA D\'AGUA AZUL de 500 L sobre o telhado, junto a cumeeira, inclinada',
          'beiral com pontas de caibro/tabica aparecendo por baixo, avancando sobre o muro',
          'bananeira e arbusto crescendo por tras da cumeeira',
          'portao/porta metalica pintada de verde-acinzentado na divisa esquerda, cortada pela quina',
          'degrau nitido no topo do muro na divisa direita',
        ],
        fotos: [
          'foto-31',
        ],
        confianca: 'alta',
        _: 'Muro no alinhamento, 2,2 m, CHAPISCO GROSSO CRU sem pintura, muito rugoso, bege-acinzentado (#c4b092 no sol, #8e7a60 na sombra); a parte de baixo (ate',
      },
      {
        id: 'josino-muro-alto-trepadeira',
        numero: 's/n',
        ordem: 9,
        ladoDaRua: 'oposto',
        frente: 7,
        tipo: 'muro-cego',
        muro: {
          altura: 2.6,
          cor: '#bfae90',
          acabamento: 'chapisco grosso cru sem pintura, pilastra saliente na divisa, juntas de bloco aparentes no topo',
          concertina: false,
        },
        extras: [
          'trepadeira verde-escura despencando por cima do muro, cobrindo 2,5 m do pano',
          'degrau de 40 cm no topo do muro em relacao ao vizinho 281',
          'pilastra vertical saliente marcando a divisa',
          'pequeno vao/nicho escuro aberto no proprio muro',
        ],
        arvores: [
          {
            especie: 'mangueira',
            altura: 5.5,
            offsetX: 1,
            ondeFica: 'quintal',
          },
        ],
        fotos: [
          'foto-31',
        ],
        confianca: 'alta',
        _: 'Lote imediatamente depois do 281, com o muro 40 cm MAIS ALTO que o vizinho (2,6 m) - o degrau no perfil do topo tem que aparecer bem. Mesmo CHAPISCO G',
      },
      {
        id: 'josino-porta-vermelha',
        numero: 's/n',
        ordem: 10,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.4,
          cor: '#c6bba6',
          acabamento: 'reboco claro encardido sem pintura, com remendo retangular de reboco cinza mais escuro na parte baixa',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-batente',
            largura: 1,
            altura: 2.1,
            cor: '#c2543a',
            ferrugem: 0.15,
            offsetX: 0,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 0,
          profundidade: 9,
          parede: '#c6bba6',
          telha: 'ceramica colonial #b5623a',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#b5623a',
          beiral: 0.3,
          cumeeira: 4,
        },
        extras: [
          'porta pedestre de chapa vermelho-alaranjada embutida no muro',
          'CAIXA D\'AGUA AZUL quadrada sobre suporte, acima da cumeeira',
          'remendo retangular de reboco cinza na parte baixa do muro',
          'mato na junta da calcada e desnivel no passeio',
        ],
        fotos: [
          'foto-31',
        ],
        confianca: 'media',
        _: 'Casa com a fachada/muro no alinhamento, ~2,4 m, em reboco claro encardido (#c6bba6) com um grande REMENDO retangular de reboco cinza mais escuro (#9a9',
      },
      {
        id: 'josino-muro-verde',
        numero: 's/n',
        ordem: 11,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2,
          cor: '#8fae7e',
          acabamento: 'reboco liso pintado de verde-claro/verde-agua, coroamento reto, base suja de terra vermelha subindo 30 cm',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.6,
            altura: 2.1,
            cor: '#dcd8ce',
            ferrugem: 0.1,
            offsetX: 1.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 2,
          profundidade: 9,
          parede: '#dcd3bf',
          telha: 'ceramica colonial #c06a3c',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas de baixa inclinacao',
          cor: '#c06a3c',
          beiral: 0.4,
          cumeeira: 4,
        },
        extras: [
          'muro pintado de verde-agua, unica cor de parede da fileira',
          'base do muro suja de terra vermelha subindo 30 cm',
          'lance de parede clara aparecendo entre o topo do muro e o telhado',
        ],
        fotos: [
          'foto-27',
        ],
        confianca: 'media',
        _: 'Lote que QUEBRA a sequencia de muros crus: muro no alinhamento de 2,0 m, reboco liso e PINTADO de VERDE-CLARO/verde-agua (#8fae7e, sombra #6f9163), em',
      },
      {
        id: 'josino-portao-amarelo',
        numero: 's/n',
        ordem: 12,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#b0a48c',
          acabamento: 'reboco cru cinza-bege sem pintura, juntas e remendos de argamassa, caixa de padrao de energia embutida',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3,
            altura: 2.1,
            cor: '#c9a12c',
            ferrugem: 0.2,
            offsetX: 0,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 3,
          profundidade: 9,
          parede: '#dcd3bf',
          telha: 'ceramica colonial #bd6a3d',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas de baixa inclinacao',
          cor: '#bd6a3d',
          beiral: 0.4,
          cumeeira: 4.2,
        },
        extras: [
          'portao de garagem amarelo-ouro de chapa ondulada vertical',
          'soleira de concreto claro formando degrau na calcada em frente ao portao',
          'caixa de padrao de energia cinza embutida no muro a 1,3 m do chao',
        ],
        fotos: [
          'foto-27',
        ],
        confianca: 'media',
        _: 'Muro no alinhamento de 2,2 m em reboco cru cinza-bege sem pintura (#b0a48c), com juntas e remendos, e no meio dele um PORTAO DE GARAGEM de chapa metal',
      },
      {
        id: 'josino-vizinha-esquina',
        numero: 's/n',
        ordem: 13,
        ladoDaRua: 'oposto',
        frente: 8,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.2,
          cor: '#b9b6ae',
          acabamento: 'reboco cru cinza-claro sem pintura, mais liso que os vizinhos, caixa escura embutida a 1,5 m',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 2.8,
            altura: 2.2,
            cor: '#c2bdb4',
            ferrugem: 0.4,
            offsetX: -0.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.7,
          recuo: 2.5,
          profundidade: 9,
          parede: '#d8cdb4',
          telha: 'ceramica colonial #c06a3c',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas',
          cor: '#c06a3c',
          beiral: 0.4,
          cumeeira: 4.2,
        },
        extras: [
          'ferrugem alaranjada subindo 30 cm da base do portao de chapa',
          'caixa escura pequena (medidor/campainha) embutida no muro',
          'monte de areia e entulho encostado no pe do muro, na calcada',
        ],
        fotos: [
          'foto-27',
        ],
        confianca: 'media',
        _: 'Ultimo lote antes da esquina. Muro no alinhamento de 2,2 m em reboco cru cinza-claro sem pintura (#b9b6ae), mais liso e mais claro que os vizinhos, co',
      },
      {
        id: 'josino-esquina-pedra',
        numero: 's/n',
        ordem: 14,
        ladoDaRua: 'oposto',
        frente: 12,
        tipo: 'casa-com-muro',
        muro: {
          altura: 2.5,
          cor: '#a67a4e',
          acabamento: 'alvenaria rustica sem reboco, textura pedregosa irregular ocre-marrom com juntas de argamassa aparentes, pilastras rebocadas claras salientes a cada 3 m',
          concertina: false,
        },
        portoes: [
          {
            tipo: 'chapa-correr',
            largura: 3.5,
            altura: 2.2,
            cor: '#e0dcd4',
            ferrugem: 0.1,
            offsetX: 3.5,
          },
        ],
        casa: {
          pavimentos: 1,
          pedireito: 2.9,
          recuo: 1.2,
          profundidade: 11,
          parede: '#c98a6b',
          telha: 'ceramica colonial gasta #b96139 / #a35431',
          varanda: false,
        },
        telhado: {
          tipo: 'duas aguas com oitao/frontao triangular voltado para a rua, um pano em tacanica na esquina',
          cor: '#b96139',
          beiral: 0.45,
          cumeeira: 4.5,
        },
        extras: [
          'PARABOLICA branca de tela de ~1,8 m sobre o telhado, em mastro - silhueta que fecha o quarteirao',
          'BOUGAINVILLE derramando flores lilas-rosadas por cima do muro na quina',
          'muro de alvenaria rustica sem reboco com pilastras rebocadas claras',
          'portao branco de chapa corrugada na face da rua transversal',
          'empena/oitao triangular pintado de salmao-terracota',
          'calcada de esquina larga com raio de 5 m e laje de concreto clara recente em frente ao portao',
        ],
        fotos: [
          'foto-27',
          'foto-32',
        ],
        confianca: 'alta',
        _: 'LOTE DE ESQUINA, o marco do fim do quarteirao - o muro dobra e continua pela rua transversal. Muro alto de 2,4 a 2,6 m em ALVENARIA RUSTICA SEM REBOCO',
      },
    ],
  },
}

export default PLANTA
